# Theme name.
theme: tiny

# site globals
site:
  url: http://wave-developers.github.io
  name: Wave Developers
  description: Wave developers meetup communitry
  build: dist
  keywords: balkan,albania,bosnia and herzegovina,croatia,makedonia,montenegro,serbia,events,programming,java,javascript,python,ruby,c,angularjs,nodejs,ionj,startup,DIY

# Main menu
menus:
  - name: Call 4 Speakers
    url: /call.html

  - name: Support Us
    url: /support.html

  - name: Contact
    url: /contact.html

  - name: About
    url: /about.html

# next event

next:
  loc:
    lat: 42.453247
    lng: 18.533930

# Disqus configuration, comment these lines to disable it
# Services

disqus:
  shortname: wave-develoeprs-gh-page

email:
  account: wave.developers.team@gmail.com

facebook:
  account: Wave-Developers/547751192031667
  groups:
    en: 656571341153398
    ru: ex.yu.developers

github:
  account: wave-developers

google:
  analytics: UA-38043860-8 # Google analytics
  verification: "-WuDSQXcQ3LYVkL0N9vaxK-5xrxXS4I-nB9t5qreNjU" # Google webmaster verification

twitter:
  account: hyzhak_en

youtube:
  account: UCGu3STPtjYgKHz0g4DM9Evw
