# Theme name.
theme: tiny

# site globals
site:
  url: http://wave-developers.github.io
  name: Wave Developers
  description: Wave developers meetup communitry
  build: dist/

# Main menu
menus:
  - name: Call 4 Speakers
    url: /call.html

  - name: Support
    url: /support.html

  - name: About
    url: /about.html

# Disqus configuration, comment these lines to disable it
disqus:
  shortname: wave-develoeprs-gh-page

google:
  analytics: UA-38043860-8 # Google analytics
  verification: "-WuDSQXcQ3LYVkL0N9vaxK-5xrxXS4I-nB9t5qreNjU" # Google webmaster verification

twitter:
  name: _hyzhak_en_
